### ISSUE TITLE
Update to 4.2

### ISSUE THREAD

**Issue by SaadTheGlad** [2shady4u/godot-krita-importer#2]
**Is your feature request related to a problem? Please describe.**

The plugin is not compatible with version 4.2

**Describe the solution you'd like**

Could you update this plugin to 4.2? This would be perfect for a project I'm working on. I have seen your other plugin and it seems like you're the only one who has worked on this problem.

**Describe alternatives you've considered**

If you can't make it/don't have time could you give me some pointers as to how to make it myself? I'm not skilled in C++ but maybe I could try.

**Additional context**

![image](https://github.com/2shady4u/godot-krita-importer/assets/39242060/fe5dbe3b-47f5-4bad-8975-4dc2db2c5fbd)

I have this massive skeleton file that's separated into a bunch of layers for a game mechanic I'm working on and exporting it manually into Godot messes up the layer order and it's annoying to do it manually.

**Comment by 2shady4u** [comment]
I am working on it here: https://github.com/2shady4u/godot-krita-importer/tree/feature/update-to-gdextension

**Comment by 2shady4u** [comment]
Closing issue as https://github.com/2shady4u/godot-krita-importer/releases/tag/v0.3 has been released!
