### ISSUE TITLE
Crop to visible part of layer

### ISSUE THREAD

**Issue by timkrief** [2shady4u/godot-krita-importer#4]
Hi the layer sizes were strange and not behaving as in krita (where the layer seems to have the size of the bounding rect of what's opaque)

I was able to fix that by changing some lines, I could do a merge request if you like the feature.

```gdscript

	var image = Image.create_from_data(layer_data.width, layer_data.height, false, layer_data.format, layer_data.data)
	var visible_region = image.get_used_rect()
	var cropped_image = image.get_region(visible_region);
	var texture = ImageTexture.create_from_image(cropped_image)
	
	sprite.position = layer_data.get("position", Vector2.ZERO) + Vector2(visible_region.position)
```

![image](https://github.com/user-attachments/assets/8a0138da-829e-41f8-9d0c-7b526b1a0638)

**Comment by 2shady4u** [comment]
Hello @timkrief 

Thank you for your interest in this plugin 😄 
I am a bit confused on what the issue exactly is 🤔 
Would it be possible to show me a before and after picture comparing the imported Krita file with the original Kirita file in Krita itself?

**Comment by 2shady4u** [comment]
I figured out the difference by using the 'example.kra'-file 😄
I do think it would be better if this was a parameter in the import settings (can be true by default)

**Comment by timkrief** [comment]
How should it be named?

**Comment by timkrief** [comment]
crop_layers_to_visible_bounding_rect ?

**Comment by 2shady4u** [comment]
> crop_layers_to_visible_bounding_rect ?

Seems like you have a preference for long names 😄 
`crop_to_visible`
`crop_to_visible_rect`
Are all fine choices!

**Comment by timkrief** [comment]
Updated #6 to add a parameter in the import settings ;)
