### ISSUE TITLE
Import Layers as Centered Sprites

### ISSUE THREAD

**Issue by timkrief** [2shady4u/godot-krita-importer#5]
Hi! I needed to import my layers as centered sprites. I added an import option
![image](https://github.com/user-attachments/assets/f11d295c-1e11-41dd-baee-edeb5e267071)

The code to make that work is not complicated:

```gdscript
	if options.get("import_layers_as_centered_sprites", false):
		sprite.position += Vector2(visible_region.size)/2.0
		sprite.centered = true
	else:
		sprite.centered = false
```

![image](https://github.com/user-attachments/assets/5c4312e4-489d-4171-bae2-19573a9d3511)

I could create a PR if you like the feature. :)

**Comment by timkrief** [comment]
This one kind of depends on https://github.com/2shady4u/godot-krita-importer/issues/4 So I'm not making a PR yet

**Comment by 2shady4u** [comment]
@timkrief feel free to make an MR if you like :)

**Comment by timkrief** [comment]
I made it so that it doesn't depend on the layer being cropped to visible or not.
