### ISSUE TITLE
Import sprites as files

### ISSUE THREAD

**Issue by timkrief** [2shady4u/godot-krita-importer#8]
I needed my sprites to be imported as png files into my project to be able to use them as normal images in godot. That way nodes can be copied out of the imported kra scene and used in other scenes independently. Plus they then can be compressed by godot when exporting etc.

I added an "import as files option" in the importer.

It's working really well:
![image](https://github.com/user-attachments/assets/6a9e4c7e-32ce-4c93-adad-1c9711aeab4f)

It creates a folder where all the files are and instead of using raw image data, it loads the pngs using godot load function, using a compressed version as it would do for other pngs imported into godot. It creates directories to respect layers tree.

You can see it's pointing to the png file (imported version of the png file created by godot) and no longer an ImageTexture using RAW data.
![image](https://github.com/user-attachments/assets/f28df93a-d5ef-4269-ac44-29ed4172e1ae)

ImageTexture can be efficient at runtime, but using proper images makes more sense to me if I need to export the project. Plus, that way it's easier to use imported stuff in other scenes.

**Comment by timkrief** [comment]
Since I need to use `append_import_external_resource` for this, I have to make import_paint_layer and import_group_layer non static, is this ok or was the fact that they were static important?

**Comment by 2shady4u** [comment]
> Since I need to use `append_import_external_resource` for this, I have to make import_paint_layer and import_group_layer non static, is this ok or was the fact that they were static important?

Honestly, I don't remember if there was any particular reason why I decided to make those methods static.
If you don't encounter any unexpected issues when converting those methods to non-static, then it should be ok.
